name: Create link
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        type: string
      url:
        required: true
        type: string
      tags:
        required: false
        type: string
      comment:
        required: false
        type: string
      origin_title:
        required: false
        type: string
      origin_url:
        required: false
        type: string
      published_date:
        required: false
        type: string
      automerge:
        required: false
        type: boolean
        default: true

jobs:
  prepare_labels:
    runs-on: ubuntu-latest
    name: Prepare PR labels
    outputs:
      labels: ${{ steps.set-labels.outputs.labels }}
    steps:
      - id: set-labels
        name: Set labels
        run: |
          if [[ "${{ inputs.automerge }}" == "true" ]];then
            echo "labels=automerge" >> $GITHUB_OUTPUT
          fi
  create_link:
    runs-on: ubuntu-latest
    name: Generate link post
    needs: prepare_labels
    steps:
      - uses: actions/checkout@v3
      - name: log
        run: |
          echo "Create link PR ..."
          echo "\ttitle: ${{ inputs.title }}"
          echo "\tURL: ${{ inputs.url }}"
          echo "\ttags: ${{ inputs.tags }}"
          echo "\tcomment: ${{ inputs.comment }}"
          echo "\torigin title: ${{ inputs.origin_title }}"
          echo "\torigin URL: ${{ inputs.origin_url }}"
          echo "\tpublished: ${{ inputs.published_date }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 18.2.0
      - name: create post
        run: node scripts/create-link.mjs --title="${{ inputs.title }}" --url=${{ inputs.url }} --date=${{ github.event.repository.updated_at }} --originTitle="${{ inputs.origin_title }}" --originUrl=${{ inputs.origin_url }} --comment="${{ inputs.comment }}" --publishedDate=${{ inputs.published_date }} --tags=${{ inputs.tags }}
      - name: create PR
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: "Create link ${{ inputs.url }}"
          commit-message: "Automated PR for link ${{ inputs.title }} @ ${{ inputs.url }}"
          branch: "add-link"
          branch-suffix: "timestamp"
          committer: GitHub <noreply@github.com>
          author: Ondrej Synacek <ondrej@synacek.org>
          labels: |
            ${{ needs.prepare_labels.outputs.labels }}
