name: Create link
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        type: string
      url:
        required: true
        type: string
      tags:
        required: false
        type: string
      comment:
        required: false
        type: string
      origin_title:
        required: false
        type: string
      origin_url:
        required: false
        type: string
      published_date:
        required: false
        type: string
  pull_request:
jobs:
  create_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: log
        run: |
          echo "Create link PR ..."
          echo "\ttitle: ${{ inputs.title }}"
          echo "\tURL: ${{ inputs.url }}"
          echo "\ttags: ${{ inputs.tags }}"
          echo "\tcomment: ${{ inputs.comment }}"
          echo "\torigin title: ${{ inputs.origin_title }}"
          echo "\torigin URL: ${{ inputs.origin_url }}"
          echo "\tpublished: ${{ inputs.published_date }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 18.2.0
      - name: create post
        run: node scripts/create-link.mjs --title={{ inputs.title }} --url={{ inputs.url }} --date=$(date +"%Y-%m-%dT%H:%M:%S%z") --originTitle={{ inputs.origin_title }} --originUrl={{ inputs.origin_url }} --comment={{ inputs.comment }} --publishedDate={{ inputs.published_date }} --tags={{ inputs.tags }}
